
server:
  port: 9090

spring:
  application:
    name: ECOM-APIGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ECOM-OrderService
              uri: lb://ECOM-OrderService
              predicates:
                - Path=/api/order-service/**
            - id: ECOM-InventoryService
              uri: lb://ECOM-InventoryService
              predicates:
                - Path=/api/inventory-service/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.uuid}